---
- name: Grant role {{ role_binding.role }} in {{ project.name }} to users
  command: >-
    {% if ansible_check_mode %}echo{% endif %}
    {{ oc_cmd }} adm policy -n {{ project.name }} add-role-to-user
    {% if '/' in role_binding.role %}
    --role-namespace={{ role_binding.role.split('/')[0] }}
    {{ role_binding.role.split('/')[1] }}
    {% else %}
    {{ role_binding.role }}
    {% endif %}
    {{ user }}
    {% if openshift_provision_openshift_version is version_compare('v3.9', '>=') %}
    --rolebinding-name={{ role_binding.role | replace('/', '-') }}
    {% endif %}
  with_items: "{{ role_binding.users | default([]) }}"
  loop_control:
    loop_var: user
  when: >-
    user not in current_role_users
    and (
      user is not match('system:serviceaccount:') or
      {
        'kind': 'ServiceAccount',
        'name': user.split(':')[3],
        'namespace': user.split(':')[2],
      } in current_role_service_accounts
    )
  check_mode: false
  register: command
  changed_when: >-
    command | record_change_command(change_record)

- name: Grant role {{ role_binding.role }} in {{ project.name }} to groups
  command: >
    {% if ansible_check_mode %}echo{% endif %}
    {{ oc_cmd }} adm policy -n {{ project.name }} add-role-to-group
    {% if '/' in role_binding.role %}
    --role-namespace={{ role_binding.role.split('/')[0] }}
    {{ role_binding.role.split('/')[1] }}
    {% else %}
    {{ role_binding.role }}
    {% endif %}
    {{ group }}
    {% if openshift_provision_openshift_version is version_compare('v3.9', '>=') %}
    --rolebinding-name={{ role_binding.role | replace('/', '-') }}
    {% endif %}
  with_items: "{{ role_binding.groups | default([]) }}"
  loop_control:
    loop_var: group
  when: >
    group not in current_role_groups
  check_mode: false
  register: command
  changed_when: >-
    command | record_change_command(change_record)

- name: Remove role {{ role_binding.role }} in {{ project.name }} from unlisted users
  command: >
    {% if ansible_check_mode %}echo{% endif %}
    {{ oc_cmd }} adm policy -n {{ project.name }} remove-role-from-user
    {% if '/' in role_binding.role %}
    --role-namespace={{ role_binding.role.split('/')[0] }}
    {{ role_binding.role.split('/')[1] }}
    {% else %}
    {{ role_binding.role }}
    {% endif %}
    {{ user }}
  with_items: "{{ current_role_users }}"
  loop_control:
    loop_var: user
  when: >
    ( role_binding.remove_unlisted | default(false) | bool or
      role_binding.remove_unlisted_users | default(false) | bool ) and
    user not in role_binding.users | default([])
  check_mode: false
  register: command
  changed_when: >-
    command | record_change_command(change_record)

- name: Remove role {{ role_binding.role }} in {{ project.name }} from unlisted service accounts
  command: >
    {% if ansible_check_mode %}echo{% endif %}
    {{ oc_cmd }} adm policy -n {{ project.name }} remove-role-from-user
    {% if '/' in role_binding.role %}
    --role-namespace={{ role_binding.role.split('/')[0] }}
    {{ role_binding.role.split('/')[1] }}
    {% else %}
    {{ role_binding.role }}
    {% endif %}
    {{ service_account_string }}
  with_items: "{{ current_role_service_accounts }}"
  loop_control:
    loop_var: service_account
  vars:
    service_account_string: >-
      system:serviceaccount:{{ service_account.namespace }}:{{ service_account.name }}
  when: >
    ( role_binding.remove_unlisted | default(false) | bool or
      role_binding.remove_unlisted_users | default(false) | bool ) and
    service_account_string not in role_binding.users | default([])
  check_mode: false
  register: command
  changed_when: >-
    command | record_change_command(change_record)

- name: Remove role {{ role_binding.role }} in {{ project.name }} from unlisted groups
  command: >
    {% if ansible_check_mode %}echo{% endif %}
    {{ oc_cmd }} adm policy -n {{ project.name }} remove-role-from-group
    {% if '/' in role_binding.role %}
    --role-namespace={{ role_binding.role.split('/')[0] }}
    {{ role_binding.role.split('/')[1] }}
    {% else %}
    {{ role_binding.role }}
    {% endif %}
    {{ group }}
  with_items: "{{ current_role_groups }}"
  loop_control:
    loop_var: group
  when: >
    ( role_binding.remove_unlisted | default(false) | bool or
      role_binding.remove_unlisted_groups | default(false) | bool ) and
    group not in role_binding.groups | default([])
  check_mode: false
  register: command
  changed_when: >-
    command | record_change_command(change_record)
