apiVersion: v1
kind: LimitRange
metadata:
  name: core-resource-limits
spec:
  limits:
    - type: Pod
      max:
        cpu: "16"
        memory: 16Gi
      min:
        cpu: 100m
        memory: 1Mi
    - type: Container
      max:
        cpu: "16"
        memory: 16Gi
      min:
        cpu: 100m
        memory: 1Mi
      default:
        cpu: "1"
        memory: 500Mi
      defaultRequest:
        cpu: 500m
        memory: 250Mi
      maxLimitRequestRatio:
        cpu: "10"
